kind: ConfigMap
apiVersion: v1
metadata:
  name: polynote
data:
  config.yaml: |
    listen:
      host: 0.0.0.0
      port: 8192
    # kernel:
    #   listen: 0.0.0.0
    #   portRange: 30000:30000
    spark:
      properties:
        spark.master: k8s://https://kubernetes.default.svc
        spark.kubernetes.container.image: minyk/spark:3.0.1-SNAPSHOT
        spark.driver.host: ploynote-headless
        spark.driver.port: 30000
        spark.executor.instances: 4
        spark.executor.cores: 2
        spark.executor.memory: 8g
    #    spark.driver.memory: 28g
    #    spark.executor.memory: 60g
    #    spark.driver.userClasspathFirst: true
    #    spark.executor.userClasspathFirst: true
    #  spark_submit_args: "--some --arguments"
    #  dist_classpath_filter: hadoop.*\.jar
