apiVersion: apps/v1
kind: Deployment
metadata:
  name: polynote
  labels:
    app: polynote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polynote
  template:
    metadata:
      labels:
        app: polynote
    spec:
      serviceAccountName: polynote
      containers:
      - name: polynote
        image: minyk/polynote:0.3.7-2.12-spark3.0
        args: ['--config', '/opt/config/config.yaml']
        env:
        - name: PYSPARK_ALLOW_INSECURE_GATEWAY
          value: '1'
        ports:
        - containerPort: 8192
        volumeMounts:
        - name: config-volume
          mountPath: /opt/config
        - mountPath: /opt/polynote/notebooks
          name: notebooks
      volumes:
      - name: config-volume
        configMap:
          name: polynote
      - name: notebooks
        emptyDir: {}
