kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "polynote.fullname" . }}-role
  labels:
    app.kubernetes.io/name: {{ include "polynote.name" . }}
    helm.sh/chart: {{ include "polynote.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "nodes", "nodes/proxy", "namespaces", "events"]
  verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]
