kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "polynote.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "polynote.name" . }}
    helm.sh/chart: {{ include "polynote.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
secrets:
  - name: {{ include "polynote.fullname" . }}
